// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryManagment.Data;

namespace SalaryManagment.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210629084641_SalaryMangmentmaybe")]
    partial class SalaryMangmentmaybe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("SalaryManagment.Entities.Appraisal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Percent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalaryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalaryId")
                        .IsUnique();

                    b.ToTable("Appraisals");
                });

            modelBuilder.Entity("SalaryManagment.Entities.Bonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalaryByMonthId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalaryByMonthId");

                    b.ToTable("Bonuss");
                });

            modelBuilder.Entity("SalaryManagment.Entities.Restrictions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedHoliday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedLates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HolidayDeduction")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Restrictionss");
                });

            modelBuilder.Entity("SalaryManagment.Entities.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaryBreakdownId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalaryBreakdownId");

                    b.ToTable("Salarys");
                });

            modelBuilder.Entity("SalaryManagment.Entities.SalaryBreakdown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaySalary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SalaryBreakdowns");
                });

            modelBuilder.Entity("SalaryManagment.Entities.SalaryByMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Month")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalarayDeductionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalarayDeductionsId");

                    b.HasIndex("SalaryId");

                    b.ToTable("SalaryByMonth");
                });

            modelBuilder.Entity("SalaryManagment.Entities.SalaryDeduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalaryDeductions");
                });

            modelBuilder.Entity("SalaryManagment.Entities.SalaryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalaryByMonthId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalaryByMonthId");

                    b.ToTable("SalaryHistorys");
                });

            modelBuilder.Entity("SalaryManagment.Entities.Appraisal", b =>
                {
                    b.HasOne("SalaryManagment.Entities.Salary", "Salary")
                        .WithOne("Appraisal")
                        .HasForeignKey("SalaryManagment.Entities.Appraisal", "SalaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("SalaryManagment.Entities.Bonus", b =>
                {
                    b.HasOne("SalaryManagment.Entities.SalaryByMonth", null)
                        .WithMany("Bonus")
                        .HasForeignKey("SalaryByMonthId");
                });

            modelBuilder.Entity("SalaryManagment.Entities.Salary", b =>
                {
                    b.HasOne("SalaryManagment.Entities.SalaryBreakdown", "SalaryBreakdown")
                        .WithMany()
                        .HasForeignKey("SalaryBreakdownId");

                    b.Navigation("SalaryBreakdown");
                });

            modelBuilder.Entity("SalaryManagment.Entities.SalaryByMonth", b =>
                {
                    b.HasOne("SalaryManagment.Entities.SalaryDeduction", "SalarayDeductions")
                        .WithMany()
                        .HasForeignKey("SalarayDeductionsId");

                    b.HasOne("SalaryManagment.Entities.Salary", "Salary")
                        .WithMany("SalaryByMonth")
                        .HasForeignKey("SalaryId");

                    b.Navigation("SalarayDeductions");

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("SalaryManagment.Entities.SalaryHistory", b =>
                {
                    b.HasOne("SalaryManagment.Entities.SalaryByMonth", "SalaryByMonth")
                        .WithMany("SalaryHistorys")
                        .HasForeignKey("SalaryByMonthId");

                    b.Navigation("SalaryByMonth");
                });

            modelBuilder.Entity("SalaryManagment.Entities.Salary", b =>
                {
                    b.Navigation("Appraisal");

                    b.Navigation("SalaryByMonth");
                });

            modelBuilder.Entity("SalaryManagment.Entities.SalaryByMonth", b =>
                {
                    b.Navigation("Bonus");

                    b.Navigation("SalaryHistorys");
                });
#pragma warning restore 612, 618
        }
    }
}
